
docs_dir: "./.docs/templates"
site_dir: "./.docs/output/"
site_name: "Event Processor Registry"
site_url: "http://localhost:8000"
site_description: "Register functions to be passed events from a queue"

nav:
  - Introduction: 'index.md'
  - Dispatcher: 'dispatcher.md'
  - Registry: 'handler_registry.md'
  - EventSources:
      Overview: 'EventSources/event_source_overview.md'
      KafkaEventSource: 'EventSources/kafka_source.md'


theme:
  name: "material"

plugins:
  - mermaid2
  - mkdocstrings:
      watch:
        - event_stream_processor
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("event_stream_processor")


extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js